sudo: false

language: dart

dart:
- stable
- dev

script:
  - pub get
  - pub run test -r expanded
  - dartfmt -n --set-exit-if-changed lib/
  - dartanalyzer --fatal-infos --fatal-warnings .
  - pub run main
